# -*- coding: utf-8 -*-
"""Numpy.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/14P2p_2DK5LiSXV7F3M05bHTyq2yYB6gH
"""

import numpy as np

url = 'https://raw.githubusercontent.com/alura-cursos/numpy/dados/apples_ts.csv'

dado = np.loadtxt(url, delimiter=',', usecols = np.arange(6,88,1))



dado.ndim # Verifica a quantidade de dimensões do array

dado.size # Quantidade de elementos de um array.

dado.shape # Para verificar o número de elementos em cada dimensão

dado.T # Inverter a estrutura dos nossos dados trocando as linhas por colunas

dado_transposto = dado.T

datas = dado_transposto[:,0]